steps:
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/recepku-api/recepku-api", "."]
  
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/recepku/recepku-api"]
  
    - name: "gcr.io/cloud-builders/gcloud"
      args:
        [
          "run",
          "deploy",
          "recepku-api",
          "--image",
          "gcr.io/recepku/recepku-api",
          "--allow-unauthenticated",
          "--region",
          "asia-southeast2",
        ]
  
  options:
    logging: CLOUD_LOGGING_ONLY